# coding: utf-8

THEMATIC_AREAS = sorted([
    u"agricultural sciences",
    u"applied social sciences",
    u"biological sciences",
    u"engineering",
    u"exact and earth sciences",
    u"health sciences",
    u"human sciences",
    u"linguistics, letters and arts"
])

CITABLE_DOCUMENT_TYPES = (
    'data-article',
    u'article-commentary',
    u'brief-report',
    u'case-report',
    u'rapid-communication',
    u'research-article',
    u'review-article'
)

ISO_3166 = {
    'BD': u'Bangladesh',
    'BE': u'Belgium',
    'BF': u'Burkina Faso',
    'BG': u'Bulgaria',
    'BA': u'Bosnia and Herzegovina',
    'BB': u'Barbados',
    'WF': u'Wallis and Futuna',
    'BL': u'Saint Barthélemy',
    'BM': u'Bermuda',
    'BN': u'Brunei Darussalam',
    'BO': u'Bolivia',
    'BH': u'Bahrain',
    'BI': u'Burundi',
    'BJ': u'Benin',
    'BT': u'Bhutan',
    'BU': u'Burma',
    'BV': u'Bouvet Island',
    'BW': u'Botswana',
    'WS': u'Samoa',
    'BQ': u'British Antarctic Territory',
    'BR': u'Brazil',
    'BS': u'Bahamas',
    'JE': u'Jersey',
    'WK': u'Wake Island',
    'BY': u'Byelorussian SSR',
    'BZ': u'Belize',
    'RU': u'Russian Federation',
    'RW': u'Rwanda',
    'PC': u'Pacific Islands',
    'TL': u'Timor-Leste',
    'JT': u'Johnston Island',
    'TM': u'Turkmenistan',
    'TJ': u'Tajikistan',
    'RO': u'Romania',
    'RH': u'Southern Rhodesia',
    'TK': u'Tokelau',
    'GW': u'Guinea-Bissau',
    'GU': u'Guam',
    'GT': u'Guatemala',
    'GS': u'South Georgia and the South Sandwich Islands',
    'GR': u'Greece',
    'GQ': u'Equatorial Guinea',
    'GP': u'Guadeloupe',
    'JP': u'Japan',
    'GY': u'Guyana',
    'GG': u'Guernsey',
    'GF': u'French Guiana',
    'GE': u'Gilbert and Ellice Islands',
    'GD': u'Grenada',
    'GB': u'United Kingdom',
    'GA': u'Gabon',
    'SV': u'El Salvador',
    'GN': u'Guinea',
    'GM': u'Gambia',
    'GL': u'Greenland',
    'GI': u'Gibraltar',
    'GH': u'Ghana',
    'OM': u'Oman',
    'TN': u'Tunisia',
    'JM': u'Jamaica',
    'JO': u'Jordan',
    'HR': u'Croatia',
    'HV': u'Upper Volta',
    'HT': u'Haiti',
    'HU': u'Hungary',
    'HK': u'Hong Kong',
    'HN': u'Honduras',
    'HM': u'Heard Island and McDonald Islands',
    'VD': u'Viet-Nam',
    'VE': u'Venezuela',
    'PR': u'Puerto Rico',
    'PS': u'Palestine',
    'UA': u'Ukraine',
    'PW': u'Palau',
    'PT': u'Portugal',
    'PU': u'United States Miscellaneous Pacific Islands',
    'PZ': u'Panama Canal Zone',
    'PY': u'Paraguay',
    'IQ': u'Iraq',
    'PA': u'Panama',
    'PF': u'French Polynesia',
    'PG': u'Papua New Guinea',
    'PE': u'Peru',
    'PK': u'Pakistan',
    'PH': u'Philippines',
    'PN': u'Pitcairn',
    'PL': u'Poland',
    'PM': u'Saint Pierre and Miquelon',
    'ZM': u'Zambia',
    'EH': u'Western Sahara',
    'EE': u'Estonia',
    'EG': u'Egypt',
    'ZA': u'South Africa',
    'EC': u'Ecuador',
    'IT': u'Italy',
    'VN': u'Viet Nam',
    'SB': u'Solomon Islands',
    'ET': u'Ethiopia',
    'SO': u'Somalia',
    'ZW': u'Zimbabwe',
    'SA': u'Saudi Arabia',
    'ES': u'Spain',
    'ER': u'Eritrea',
    'ME': u'Montenegro',
    'MD': u'Moldova',
    'MG': u'Madagascar',
    'MF': u'Saint Martin',
    'MA': u'Morocco',
    'MC': u'Monaco',
    'UZ': u'Uzbekistan',
    'MM': u'Myanmar',
    'ML': u'Mali',
    'MO': u'Macao',
    'MN': u'Mongolia',
    'MI': u'Midway Islands',
    'MH': u'Marshall Islands',
    'MK': u'Macedonia',
    'MU': u'Mauritius',
    'MT': u'Malta',
    'MW': u'Malawi',
    'MV': u'Maldives',
    'MQ': u'Martinique',
    'MP': u'Northern Mariana Islands',
    'MS': u'Montserrat',
    'MR': u'Mauritania',
    'IM': u'Isle of Man',
    'UG': u'Uganda',
    'TZ': u'Tanzania',
    'MY': u'Malaysia',
    'MX': u'Mexico',
    'IL': u'Israel',
    'FQ': u'French Southern and Antarctic Territories',
    'FR': u'France',
    'IO': u'British Indian Ocean Territory',
    'SH': u'Saint Helena',
    'RE': u'Réunion',
    'SJ': u'Svalbard and Jan Mayen',
    'FI': u'Finland',
    'FJ': u'Fiji',
    'FK': u'Falkland Islands',
    'FM': u'Micronesia',
    'FO': u'Faroe Islands',
    'NH': u'New Hebrides',
    'NI': u'Nicaragua',
    'NL': u'Netherlands',
    'NO': u'Norway',
    'NA': u'Namibia',
    'VU': u'Vanuatu',
    'NC': u'New Caledonia',
    'NE': u'Niger',
    'NF': u'Norfolk Island',
    'NG': u'Nigeria',
    'NZ': u'New Zealand',
    'ZR': u'Zaire',
    'NP': u'Nepal',
    'NQ': u'Dronning Maud Land',
    'NR': u'Nauru',
    'NT': u'Neutral Zone',
    'NU': u'Niue',
    'CK': u'Cook Islands',
    'CI': u"Côte d'Ivoire",
    'CH': u'Switzerland',
    'CO': u'Colombia',
    'CN': u'China',
    'CM': u'Cameroon',
    'CL': u'Chile',
    'CC': u'Cocos',
    'CA': u'Canada',
    'CG': u'Congo',
    'CF': u'Central African Republic',
    'CD': u'Congo',
    'CZ': u'Czech Republic',
    'CY': u'Cyprus',
    'CX': u'Christmas Island',
    'CS': u'Czechoslovakia',
    'CR': u'Costa Rica',
    'CW': u'Curaçao',
    'CV': u'Cabo Verde',
    'CU': u'Cuba',
    'CT': u'Canton and Enderbury Islands',
    'SZ': u'Swaziland',
    'SY': u'Syrian Arab Republic',
    'SX': u'Sint Maarten',
    'KG': u'Kyrgyzstan',
    'KE': u'Kenya',
    'SS': u'South Sudan',
    'SR': u'Suriname',
    'KI': u'Kiribati',
    'KH': u'Cambodia',
    'KN': u'Saint Kitts and Nevis',
    'KM': u'Comoros',
    'ST': u'Sao Tome and Principe',
    'SK': u'Slovakia',
    'KR': u'Korea',
    'SI': u'Slovenia',
    'KP': u'Korea',
    'KW': u'Kuwait',
    'SN': u'Senegal',
    'SM': u'San Marino',
    'SL': u'Sierra Leone',
    'SC': u'Seychelles',
    'KZ': u'Kazakhstan',
    'KY': u'Cayman Islands',
    'SG': u'Singapore',
    'SE': u'Sweden',
    'SD': u'Sudan',
    'DO': u'Dominican Republic',
    'DM': u'Dominica',
    'DJ': u'Djibouti',
    'DK': u'Denmark',
    'VG': u'Virgin Islands',
    'DD': u'German Democratic Republic',
    'DE': u'Germany',
    'YE': u'Yemen',
    'YD': u'Yemen',
    'DZ': u'Algeria',
    'US': u'United States',
    'DY': u'Dahomey',
    'UY': u'Uruguay',
    'YU': u'Yugoslavia',
    'YT': u'Mayotte',
    'UM': u'United States Minor Outlying Islands',
    'LB': u'Lebanon',
    'LC': u'Saint Lucia',
    'LA': u"Lao People's Democratic Republic",
    'TV': u'Tuvalu',
    'TW': u'Taiwan',
    'TT': u'Trinidad and Tobago',
    'TR': u'Turkey',
    'LK': u'Sri Lanka',
    'TP': u'East Timor',
    'LI': u'Liechtenstein',
    'LV': u'Latvia',
    'TO': u'Tonga',
    'LT': u'Lithuania',
    'LU': u'Luxembourg',
    'LR': u'Liberia',
    'LS': u'Lesotho',
    'TH': u'Thailand',
    'TF': u'French Southern Territories',
    'TG': u'Togo',
    'TD': u'Chad',
    'TC': u'Turks and Caicos Islands',
    'LY': u'Libya',
    'VA': u'Holy See',
    'VC': u'Saint Vincent and the Grenadines',
    'AE': u'United Arab Emirates',
    'AD': u'Andorra',
    'AG': u'Antigua and Barbuda',
    'AF': u'Afghanistan',
    'AI': u'Anguilla',
    'VI': u'Virgin Islands',
    'IS': u'Iceland',
    'IR': u'Iran',
    'AM': u'Armenia',
    'AL': u'Albania',
    'AO': u'Angola',
    'AN': u'Netherlands Antilles',
    'AQ': u'Antarctica',
    'AS': u'American Samoa',
    'AR': u'Argentina',
    'AU': u'Australia',
    'AT': u'Austria',
    'AW': u'Aruba',
    'IN': u'India',
    'AX': u'Âland Islands',
    'AZ': u'Azerbaijan',
    'IE': u'Ireland',
    'ID': u'Indonesia',
    'RS': u'Serbia',
    'QA': u'Qatar',
    'MZ': u'Mozambique'
}

ISO_3166_COUNTRY_AS_KEY = {value: key for key, value in ISO_3166.items()}