apiVersion: v1
kind: Secret
metadata:
  name: processing-env
type: Opaque
stringData:
  ARTICLEMETA_THRIFTSERVER: ""
  ARTICLEMETA_ADMINTOKEN: ""
  RATCHET_THRIFTSERVER: ""
  ACCESSSTATS_THRIFTSERVER: ""
  CITEDBY_THRIFTSERVER: ""
  PUBLICATIONSTATS_THRIFTSERVER: ""
  SOLR_SEARCH_SCIELO_ORG: ""
  SOLR_SEARCH_SCIELO_ORG_INDEX: ""
  SLACK_WEBHOOK_URL: ""
  PROCESSING_COLLECTIONS: ""
